config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'post#list'
  
  get 'post/list'
  
  get 'post/show'
  get 'post/show/:id' =>'post#show'
  
  get 'comment/write'
  post 'comment/write/:id' => 'comment#write'

  get 'comment/destroy/:id' => 'comment#destroy'

  get 'post/write'

  get 'post/new'
  post 'post/new'

  get 'post/update'
  post 'post/update/:id' => 'post#update'

  get 'post/edit'
  get 'post/edit/:id' => 'post#edit'

  get 'post/destroy'
  get 'post/destroy/:id' => 'post#destroy'
  
  get 'post/search'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/comment_controller.rb
class CommentController < ApplicationController
  before_action :authenticate_user!
  def write
    @comments = Comment.new
    @comments.user = current_user
    @comments.post_id = params[:id]
      if params[:content].empty?
        @comments.content = "댓글 내용이 없습니다."
      else
        @comments.content = params[:content]
      end
    @comments.save

    redirect_to "/post/show/#{params[:id]}"
  end

  def destroy
    @comments = Comment.find(params[:id])
    @comments.destroy

    redirect_to '/post/write'
  end
end

app/controllers/post_controller.rb
class PostController < ApplicationController
  #before_action :authenticate_user!

  def write
    @posts = Post.all.reverse
  end

  def new
    @posts = Post.new
    @posts.user = current_user
    @posts.title = params[:title]
    @posts.content = params[:content]
    @posts.save

    redirect_to "/post/list"
  end
  
  def show
    @posts = Post.find(params[:id])
  
  end
  
  def list
    @posts = Post.all.reverse
  end
  
  def update
    @posts = Post.find(params[:id])
    @posts.title = params[:title]
    @posts.content = params[:content]
    @posts.save

    redirect_to "/post/show/#{params[:id]}"
  end

  def edit
    @posts = Post.find(params[:id])
  end

  def destroy
    @posts = Post.find(params[:id])
    @posts.destroy

    redirect_to '/post/list'
  end
  
  def search
    @find_q=params[:q]
    if params[:q_value]="제목"
      @posts=Post.where("title LIKE ?","%#{@find_q}%")
    else 
      @posts=Post.where("content LIKE ?","%#{@find_q}%")
    end
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/views/comment/write.html.erb
<h1>Comment#write</h1>
<p>Find me in app/views/comment/write.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>맥주 테이스팅 노트</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
<style>

    h2{
      color: black;
      bold;
    }
      a{  
  text-decoration: none;
  text-decoration-line: none
      }
  
 table {
    border-collapse: collapse;
    width: 100%;
}

 form {
  align: center;}

th, td {  
    text-align: center;
    padding: 8px;
}  
body { background: url(/assets/호가든.jpg) no-repeat center center / cover;
    opacity: 0.85; max-height: 100%;}
    
</style>
</head>
<body>
  <%= yield %>
<div style="
    width: 100%;
    height: 100vh;
    background: url(/assets/호가든.jpeg) no-repeat center center / cover;
    opacity: 0.85;
    display: flex;
    align-items: center;
    justify-content: center;">

</div>

</body>
</html>

app/views/post/_nav.html.erb
<nav class="navbar navbar-toggleable-md navbar-light bg-faded" style="background-color: #f0ad4e;" >
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="/post/list">맥주 테이스팅 노트</a>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a href="#">
          <span class="sr-only">(current)</span>
        </a>
      </li>
    </ul>
    <div class="my-auto" style="padding-right: 10px;">
        <% if user_signed_in? %>
            <%= link_to '로그아웃', destroy_user_session_path, method: 'get' %>
            <%= link_to '글 등록', post_write_path, method: 'get' %>
        <% else %>
            <a href="/users/sign_in" style="padding-right: 10px;">로그인</a>
            <a href="/users/sign_up" style="padding-right: 10px;">회원가입</a>
        <% end %>
        </div>
  </div>
</nav>

app/views/post/destroy.html.erb
<h1>Post#destroy</h1>
<p>Find me in app/views/post/destroy.html.erb</p>

app/views/post/edit.html.erb
<%= render "nav" %>
<!-- navbar begin -->
<!--  <nav class="navbar navbar-toggleable-md navbar-light bg-faded">-->
<!--    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">-->
<!--      <span class="navbar-toggler-icon"></span>-->
<!--    </button>-->
<!--    <a class="navbar-brand" href="#">SNS</a>-->

<!--    <div class="collapse navbar-collapse" id="navbarSupportedContent">-->
<!--      <ul class="navbar-nav mr-auto">-->
<!--        <li class="nav-item active">-->
<!--          <a class="nav-link" href="/post/write">자유게시판 <span class="sr-only">(current)</span></a>-->
<!--        </li>-->
<!--      </ul>-->
<!--      <div class="my-auto" style="padding-right: 10px;">-->
<!--        <% if user_signed_in? %>-->
<!--          <%= current_user.name %>-->
<!--          <%= link_to 'Edit', edit_user_registration_path, method: 'get' %>-->
<!--          <%= link_to 'Sign Out', destroy_user_session_path, method: 'get' %>-->
<!--        <% else %>-->
<!--          <a href ="/users/sign_in" style="padding-right: 10px;">Sign In</a>-->
<!--          <a href ="/users/sign_up">Sign Up</a>-->
<!--        <% end %>-->
<!--      </div>-->
<!--      <form class="form-inline my-2 my-lg-0">-->
<!--        <input class="form-control mr-sm-2" type="text" placeholder="Search">-->
<!--        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>-->
<!--      </form>-->
<!--    </div>-->
<!--  </nav>-->
<!-- navbar end -->

<!-- container begin -->
  <div class="container" style="margin-top:50px;">

    <!-- write form begin -->
      <form action="/post/update/<%= @posts.id %>" method="POST" style="margin-bottom:15px; padding-top: 10px;padding-right: 10px;padding-bottom: 10px;padding-left: 10px; border:1px solid">
        <div class="form-group">
          <label for="exampleInputEmail1">제목</label>
          <input name="title" value="<%= @posts.title %>"type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="제목을 입력하세요.">
        </div>
        <div class="form-group">
          <label for="exampleTextarea">내용</label>
          <textarea name="content" class="form-control" id="exampleTextarea" rows="5" placeholder="제목을 입력하세요."><%= @posts.content %></textarea>
        </div>
        <% if user_signed_in? %>
            <div style="text-align:right; margin-bottom:50px;">
              <button type="submit" class="btn btn-primary">작성하기</button>
            </div>
        <% end %>
      </form>
    <!-- write form end -->

  </div>
<!-- container end -->

app/views/post/list.html.erb
<%= render "nav" %>

<div class="container" style="margin-top:50px;">
    
    <table class="table table-hover">
        <thead>
            <tr>
                <th>#</th>
                <th>제목</th>
                <th>작성자</th>
                <th>작성시간</th>
            </tr>
        </thead>
        <tbody>
            <% @posts.each do |p| %>
            <tr>
                <th scope="row"><%= p.id %></th>
                <th><a href= "/post/show/<%= p.id %>"><%= p.title %></a></th>
                <td><%= p.user.name %></td>
                <td><%= p.created_at.to_s.split("+").first %></td>
            </tr>
            <% end %>
        </tbody>
        
        
        
    </table>
 
    
<!--<% @posts.each do |p| %>-->
<!--  <div class="alert alert-default" role="alert" style="border:1px solid">-->
<!--    <h5><%= p.user.name %></h5><br/>-->
<!--    <h2><%= p.title %></h2>-->
<!--    <br/>-->
<!--    <h5><%= simple_format(p.content) %></h5>-->
<!--    <% if user_signed_in? %>-->
<!--    <div style="text-align:right;">-->
<!--      <a href="/post/edit/<%= p.id %>">-->
<!--        <span class="badge badge-default">수정</span>-->
<!--      </a>-->
<!--      <a href="/post/destroy/<%= p.id %>">-->
<!--        <span class="badge badge-danger">삭제</span>-->
<!--      </a>-->
<!--    </div>-->
<!--    <% end %>-->

<!--    <hr>-->
<!--    <% p.comments.each do |c| %>-->
<!--    <p>-->
<!--      <%= c.user.name %> : <%= c.content %>-->
      <!-- <a href="/comment/destroy/<%= c.id %>">[X]</a> -->
<!--    </p>-->
<!--    <% end %>-->

    <!-- comment form begin -->
<!--    <form action="/comment/write/<%= p.id %>" method="POST">-->
<!--      <div class="form-group" style="margin-top:10px;">-->
<!--        <label for="exampleTextarea">댓글 달기</label>-->
<!--        <textarea name="content" class="form-control" id="exampleTextarea" rows="1" placeholder="댓글을 입력하세요."></textarea>-->
<!--      </div>-->
<!--      <% if user_signed_in? %>-->
<!--      <div style="text-align:right; margin-bottom:5px;">-->
<!--        <button type="submit" class="btn btn-primary">작성하기</button>-->
<!--      </div>-->
<!--      <% end %>-->
<!--    </form>-->
    <!-- comment form end -->

<!--  </div>-->
<!-- <% end %>-->
     <div style="text-align:right;">
       <a href='/post/write'><button type="submit" class="btn btn-warning">글 쓰기</button></a>
   </div>
 </div>

app/views/post/new.html.erb
<%= render "nav" %>

app/views/post/search.html.erb
<!-- navbar begin -->
<nav class="navbar navbar-toggleable-md navbar-light bg-faded">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="#">SNS</a>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/post/write">자유게시판
          <span class="sr-only">(current)</span>
        </a>
      </li>
    </ul>
    <div class="my-auto" style="padding-right: 10px;">
      <% if user_signed_in? %>
      <%= current_user.name %>
      <%= link_to 'Edit', edit_user_registration_path, method: 'get' %>
      <%= link_to 'Sign Out', destroy_user_session_path, method: 'get' %>
    <% else %>
      <a href="/users/sign_in" style="padding-right: 10px;">Sign In</a>
      <a href="/users/sign_up">Sign Up</a>
      <% end %>
    </div>
    <form class="form-inline my-2 my-lg-0" action="/post/search" method="get">
      <div name="q_value" class="form-group">
        <select class="form-control" id="exampleSelect1">
          <option value="제목">제목</option>
          <option value="내용">내용</option>
        </select>
      </div>                   
      <input name="q" class="form-control mr-sm-2" type="text" placeholder="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
<!-- navbar end -->

<!-- container begin -->
<div class="container" style="margin-top:50px;">

  <!-- write form begin -->
  <form action="/post/new" method="POST" style="margin-bottom:15px; padding-top: 10px;padding-right: 10px;padding-bottom: 10px;padding-left: 10px; border:1px solid">
    <div class="form-group">
      <label for="exampleInputEmail1">제목</label>
      <input name="title" type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="제목을 입력하세요.">
    </div>
    <div class="form-group">
      <label for="exampleTextarea">내용</label>
      <textarea name="content" class="form-control" id="exampleTextarea" rows="5" placeholder="제목을 입력하세요."></textarea>
    </div>
    <% if user_signed_in? %>
    <div style="text-align:right; margin-bottom:50px;">
      <button type="submit" class="btn btn-primary">작성하기</button>
    </div>
    <% end %>
  </form>
  <!-- write form end -->

  <!-- list form begin -->
  <% @posts.each do |p| %>
  <div class="alert alert-default" role="alert" style="border:1px solid">
    <h5><%= p.user.name %></h5><br/>
    <h2><%= p.title %></h2>
    <br/>
    <h5><%= simple_format(p.content) %></h5>
    <% if user_signed_in? %>
    <div style="text-align:right;">
      <a href="/post/edit/<%= p.id %>">
        <span class="badge badge-default">수정</span>
      </a>
      <a href="/post/destroy/<%= p.id %>">
        <span class="badge badge-danger">삭제</span>
      </a>
    </div>
    <% end %>

    <hr>
    <% p.comments.each do |c| %>
    <p>
      <%= c.user.name %> : <%= c.content %>
      <!-- <a href="/comment/destroy/<%= c.id %>">[X]</a> -->
    </p>
    <% end %>

    <!-- comment form begin -->
    <form action="/comment/write/<%= p.id %>" method="POST">
      <div class="form-group" style="margin-top:10px;">
        <label for="exampleTextarea">댓글 달기</label>
        <textarea name="content" class="form-control" id="exampleTextarea" rows="1" placeholder="댓글을 입력하세요."></textarea>
      </div>
      <% if user_signed_in? %>
      <div style="text-align:right; margin-bottom:5px;">
        <button type="submit" class="btn btn-primary">작성하기</button>
      </div>
      <% end %>
    </form>
    <!-- comment form end -->

  </div>
  <% end %>
  <!-- list form end -->

</div>
<!-- container end -->

app/views/post/show.html.erb
<%= render "nav" %>
<div class = "container" style="margin-top:50px;">
   
    <h2><%= @posts.title %></h2>
    <hr>
    <div style="text-align:right">
        <h4><%= @posts.created_at.to_s.split("+").first %></h4>
        <h3><%= @posts.user.email %></h3>
        <div style="margin-top:20px; margin-bottom:50px;">
                <a href="/post/edit/<%= @posts.id %>"><button type="submit" class="btn btn-warning">수정</button></a>
                <a href="/post/destroy/<%= @posts.id %>"><button type="submit" class="btn btn-danger">삭제</button></a>
        </div>
    </div>
    <h4 style="margin-bottom:50px;"><%= simple_format(@posts.content) %></h4>
    
     <hr>
    <% @posts.comments.each do |c| %>
    <p>
      <%= c.user.name %> : <%= c.content %>
       <a href="/comment/destroy/<%= c.id %>">[X]</a> 
    </p>
    <% end %>

     <!--comment form begin -->
    <form action="/comment/write/<%= @posts.id %>" method="POST">
      <div class="form-group" style="margin-top:10px;">
        <label for="exampleTextarea">댓글 달기</label>
        <textarea name="content" class="form-control" id="exampleTextarea" rows="1" placeholder="댓글을 입력하세요."></textarea>
      </div>
      <% if user_signed_in? %>
      <div style="text-align:right; margin-bottom:5px;">
        <button type="submit"class="btn btn-warning">작성하기</button>
      </div>
      <% end %>
    </form>
    <div style="text-align:right">
        <a href='/post/list'><button type="submit" class="btn btn-warning">목록</button></a>
    </div>
</div>

app/views/post/update.html.erb
<%= render "nav" %>

app/views/post/write.html.erb
<%= render "nav" %>
<!-- navbar begin -->
<!--<nav class="navbar navbar-toggleable-md navbar-light bg-faded">-->
<!--  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">-->
<!--    <span class="navbar-toggler-icon"></span>-->
<!--  </button>-->
<!--  <a class="navbar-brand" href="#">SNS</a>-->

<!--  <div class="collapse navbar-collapse" id="navbarSupportedContent">-->
<!--    <ul class="navbar-nav mr-auto">-->
<!--      <li class="nav-item active">-->
<!--        <a class="nav-link" href="/post/write">자유게시판-->
<!--          <span class="sr-only">(current)</span>-->
<!--        </a>-->
<!--      </li>-->
<!--    </ul>-->
<!--    <div class="my-auto" style="padding-right: 10px;">-->
<!--      <% if user_signed_in? %>-->
<!--      <%= current_user.name %>-->
<!--      <%= link_to 'Edit', edit_user_registration_path, method: 'get' %>-->
<!--      <%= link_to 'Sign Out', destroy_user_session_path, method: 'get' %>-->
<!--    <% else %>-->
<!--      <a href="/users/sign_in" style="padding-right: 10px;">Sign In</a>-->
<!--      <a href="/users/sign_up">Sign Up</a>-->
<!--      <% end %>-->
<!--    </div>-->
<!--    <form class="form-inline my-2 my-lg-0" action="/post/search" method="get">-->
<!--      <div name="q_value" class="form-group">-->
<!--        <select class="form-control" id="exampleSelect1">-->
<!--          <option value="제목">제목</option>-->
<!--          <option value="내용">내용</option>-->
<!--        </select>-->
<!--      </div>                   -->
<!--      <input name="q" class="form-control mr-sm-2" type="text" placeholder="Search">-->
<!--      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>-->
<!--    </form>-->
<!--  </div>-->
<!--</nav>-->
<!-- navbar end -->

<!-- container begin -->
<div class="container" style="margin-top:50px;">

  <!-- write form begin -->
  <form action="/post/new" method="POST" style="margin-bottom:15px; padding-top: 10px;padding-right: 10px;padding-bottom: 10px;padding-left: 10px; border:1px solid">
    <div class="form-group">
      <label for="exampleInputEmail1">제목</label>
      <input name="title" type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="제목을 입력하세요.">
    </div>
    <div class="form-group">
      <label for="exampleTextarea">내용</label>
      <textarea name="content" class="form-control" id="exampleTextarea" rows="5" placeholder="제목을 입력하세요."></textarea>
    </div>
    <!--<% if user_signed_in? %>-->
    <div style="text-align:right; margin-bottom:50px;">
      <button type="submit" class="btn btn-warning">작성하기</button>
    </div>
    <!--<% end %>-->
  </form>
  <!-- write form end -->

  <!-- list form begin -->
  <!--<% @posts.each do |p| %>-->
  <!--<div class="alert alert-default" role="alert" style="border:1px solid">-->
  <!--  <h5><%= p.user.name %></h5><br/>-->
  <!--  <h2><%= p.title %></h2>-->
  <!--  <br/>-->
  <!--  <h5><%= simple_format(p.content) %></h5>-->
  <!--  <% if user_signed_in? %>-->
  <!--  <div style="text-align:right;">-->
  <!--    <a href="/post/edit/<%= p.id %>">-->
  <!--      <span class="badge badge-default">수정</span>-->
  <!--    </a>-->
  <!--    <a href="/post/destroy/<%= p.id %>">-->
  <!--      <span class="badge badge-danger">삭제</span>-->
  <!--    </a>-->
  <!--  </div>-->
  <!--  <% end %>-->

  <!--  <hr>-->
  <!--  <% p.comments.each do |c| %>-->
  <!--  <p>-->
  <!--    <%= c.user.name %> : <%= c.content %>-->
      <!-- <a href="/comment/destroy/<%= c.id %>">[X]</a> -->
  <!--  </p>-->
  <!--  <% end %>-->

    <!-- comment form begin -->
  <!--  <form action="/comment/write/<%= p.id %>" method="POST">-->
  <!--    <div class="form-group" style="margin-top:10px;">-->
  <!--      <label for="exampleTextarea">댓글 달기</label>-->
  <!--      <textarea name="content" class="form-control" id="exampleTextarea" rows="1" placeholder="댓글을 입력하세요."></textarea>-->
  <!--    </div>-->
  <!--    <% if user_signed_in? %>-->
  <!--    <div style="text-align:right; margin-bottom:5px;">-->
  <!--      <button type="submit" class="btn btn-primary">작성하기</button>-->
  <!--    </div>-->
  <!--    <% end %>-->
  <!--  </form>-->
    <!-- comment form end -->

  <!--</div>-->
  <!--<% end %>-->
  <!-- list form end -->

</div>
<!-- container end -->